name: CI Tests

on: ["push"]

jobs:
  tests:
    runs-on: ["ubuntu-latest"]

    strategy:
      matrix:
        node-versions: ["18.x", "16.x", "14.x"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: BACKEND - npm install
        run: cd ./server && npm ci
      - name: BACKEND - test
        run: npm run backend-test
      - name: FRONTEND - npm install
        run: cd ./client && npm ci
      - name: FRONTEND - test
        run: cd ./client && npm run test
